lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # Path to the private key
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # Path to the public key
    pass_phrase: '%env(JWT_PASSPHRASE)%' # Passphrase for the private key
    token_ttl: 3600 # Token time to live (in seconds)
